import styles from "../page.module.css"
import Image from "next/image";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import Carrusel from "@/components/Carrusel";



export const metadata = {
    title: "Section list",
    description: "Generated by create next app",
  };

export default function Home() {
    return (

        <main className={styles.main}>
            <Header></Header>            
            <Carrusel></Carrusel>
            <Footer></Footer>
        </main>
    );
}
